# Generated by Django 4.1.1 on 2022-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_number', models.IntegerField(primary_key=True, serialize=False)),
                ('device_uuid', models.SlugField(unique=True)),
            ],
        ),
    ]
